//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public SanPham()
        {
            this.CTHDs = new HashSet<CTHD>();
        }
    
        public int MaSP { get; set; }
        public string TenSP { get; set; }
        public string DVT { get; set; }
        public Nullable<int> DonGia { get; set; }
        public Nullable<int> SoTon { get; set; }
    
        public virtual ICollection<CTHD> CTHDs { get; set; }
    }
}
